package com.labz04.omri.uwimaps.shortestpath;

import android.app.Activity;

/**
 * Created by Omri on 7/11/2015.
 */
public class Dijkstra extends Activity
{


        public  Graph.Edge[] GRAPH = {
                new Graph.Edge("Student Administration Services","Assembly Hall",63),
                new Graph.Edge("Student Administration Services","NELT",85),
                new Graph.Edge("Student Administration Services","Main Library",166),
                new Graph.Edge("Student Administration Services","Book Shop",136),
                new Graph.Edge("Student Administration Services","Juici Patties",154),
                new Graph.Edge("Student Administration Services","Inter-faculty Lecture Theater",137),
                new Graph.Edge("Student Administration Services","Mona School of Business South",71),
                new Graph.Edge("Student Administration Services","Social Science Stall",102),
                new Graph.Edge("Mona Information Technology Services","Phillip Sherlock",151),
                new Graph.Edge("Mona Information Technology Services","CARIMAC",178),
                new Graph.Edge("Mona Information Technology Services","Office of Student Services and Development",183),
                new Graph.Edge("Mona Information Technology Services","Students Union",338),
                new Graph.Edge("Mona Information Technology Services","School of Nursing",200),
                new Graph.Edge("Mona Information Technology Services","U.W.I Credit Union",230),
                new Graph.Edge("Placement & Careers","News Talk",10),
                new Graph.Edge("Placement & Careers","Book Shop",15),
                new Graph.Edge("Placement & Careers","National Commercial Bank",30),
                new Graph.Edge("Placement & Careers","U.W.I Chapel",150),
                new Graph.Edge("Placement & Careers","BeeHive",150),
                new Graph.Edge("U.W.I Chapel","Book Shop",174),
                new Graph.Edge("U.W.I Chapel","CARIMAC",74),
                new Graph.Edge("U.W.I Chapel","Office of Student Services and Development",44),
                new Graph.Edge("U.W.I Chapel","Chemistry Main Office",174),
                new Graph.Edge("U.W.I Chapel","Lodgings",144),
                new Graph.Edge("U.W.I Chapel","Placement & Careers",100),
                new Graph.Edge("Book Shop","Assembly Hall",82),
                new Graph.Edge("Book Shop","Juici Patties",167),
                new Graph.Edge("Book Shop","U.W.I Chapel",67),
                new Graph.Edge("Book Shop","News Talk",17),
                new Graph.Edge("Book Shop","Placement & Careers",16),
                new Graph.Edge("National Commercial Bank","Book Shop",3),
                new Graph.Edge("National Commercial Bank","News Talk",3),
                new Graph.Edge("National Commercial Bank","U.W.I Chapel",62),
                new Graph.Edge("National Commercial Bank","NELT",162),
                new Graph.Edge("Bank of Nova Scotia","Commuting Students Lounge",121),
                new Graph.Edge("Bank of Nova Scotia","Kentucky Fried Chicken",63),
                new Graph.Edge("Bank of Nova Scotia","Main Library",157),
                new Graph.Edge("Bank of Nova Scotia","Main Library Stall",101),
                new Graph.Edge("Bank of Nova Scotia","Assembly Hall",81),
                new Graph.Edge("Bank of Nova Scotia","Mary Seacole Hall Office",70),
                new Graph.Edge("Bank of Nova Scotia","Block Aye",80),
                new Graph.Edge("Bank of Nova Scotia","School of Nursing",90),
                new Graph.Edge("Students Union","138 Office",70),
                new Graph.Edge("Students Union","New Post Grad",112),
                new Graph.Edge("Students Union","The Spot",17),
                new Graph.Edge("Students Union","Yao",5),
                new Graph.Edge("Students Union","Mona Information Technology Services",300),
                new Graph.Edge("Students Union","School of Nursing",270),
                new Graph.Edge("Students Union","Cluster 4",150),
                new Graph.Edge("Students Union","Preston Hall Office",120),
                new Graph.Edge("Students Union","UWI Health Center",300),
                new Graph.Edge("Bursary","Student Administration Services",15),
                new Graph.Edge("Bursary","Assembly Hall",63),
                new Graph.Edge("Bursary","NELT",85),
                new Graph.Edge("Bursary","Main Library",166),
                new Graph.Edge("Bursary","Book Shop",136),
                new Graph.Edge("Bursary","Juici Patties",154),
                new Graph.Edge("Bursary","Inter-faculty Lecture Theater",137),
                new Graph.Edge("Bursary","Mona School of Business South",71),
                new Graph.Edge("Bursary","School of Education",100),
                new Graph.Edge("Bursary","Social Science Stall",102),
                new Graph.Edge("Lodgings","Mona Information Technology Services",183),
                new Graph.Edge("News Talk","BeeHive",33),
                new Graph.Edge("News Talk","Book Shop",13),
                new Graph.Edge("News Talk","Juici Patties",133),
                new Graph.Edge("News Talk","Phillip Sherlock",93),
                new Graph.Edge("Phillip Sherlock","BeeHive",64),
                new Graph.Edge("Phillip Sherlock","CARIMAC",12),
                new Graph.Edge("Phillip Sherlock","U.W.I Chapel",54),
                new Graph.Edge("Phillip Sherlock","News Talk",69),
                new Graph.Edge("CARIMAC","Phillip Sherlock",12),
                new Graph.Edge("CARIMAC","BeeHive",165),
                new Graph.Edge("CARIMAC","U.W.I Chapel",65),
                new Graph.Edge("CARIMAC","Mona Information Technology Services",150),
                new Graph.Edge("Office of Student Services and Development","Mona Information Technology Services",183),
                new Graph.Edge("Commuting Students Lounge","Humanities Stall",183),
                new Graph.Edge("Commuting Students Lounge","Main Library Stall",73),
                new Graph.Edge("Commuting Students Lounge","N 1",53),
                new Graph.Edge("Commuting Students Lounge","N 2",56),
                new Graph.Edge("Commuting Students Lounge","Bank of Nova Scotia",103),
                new Graph.Edge("Commuting Students Lounge","Mary Seacole Hall Office",40),
                new Graph.Edge("Assembly Hall","Book Shop",82),
                new Graph.Edge("Assembly Hall","Student Administration Services",82),
                new Graph.Edge("Assembly Hall","Main Library",160),
                new Graph.Edge("Assembly Hall","Juici Patties",154),
                new Graph.Edge("Assembly Hall","NELT",85),
                new Graph.Edge("Assembly Hall","Inter-faculty Lecture Theater",137),
                new Graph.Edge("Chemistry Main Office","Math Main Office",73),
                new Graph.Edge("Chemistry Main Office","U.W.I Chapel",173),
                new Graph.Edge("Chemistry Main Office","Chemistry Physics Lecture Theater",33),
                new Graph.Edge("Chemistry Main Office","Chemistry Lecture Theater 1",93),
                new Graph.Edge("Chemistry Main Office","Chemistry Lecture Theater 2",83),
                new Graph.Edge("Chemistry Lecture Theater 1","Chemistry Main Office",63),
                new Graph.Edge("Chemistry Lecture Theater 2","Chemistry Main Office",60),
                new Graph.Edge("Chemistry Lecture Theater 3","Chemistry Main Office",55),
                new Graph.Edge("Chemistry Lecture Theater 4","Chemistry Main Office",50),
                new Graph.Edge("Chemistry Lecture Theater 5","Math Main Office",88),
                new Graph.Edge("Chemistry Lecture Theater 5","Chemistry Lecture Theater 6",20),
                new Graph.Edge("Chemistry Lecture Theater 5","Chemistry Lecture Theater 7",25),
                new Graph.Edge("Chemistry Lecture Theater 6","Math Main Office",23),
                new Graph.Edge("Chemistry Lecture Theater 7","Math Main Office",20),
                new Graph.Edge("Chemistry Physics Lecture Theater","Chemistry Main Office",10),
                new Graph.Edge("Chemistry Physics Lecture Theater","U.W.I Chapel",183),
                new Graph.Edge("Chemistry Physics Lecture Theater","Earthquake Unit",10),
                new Graph.Edge("Chemistry Physics Lecture Theater","Virtual Lab",10),
                new Graph.Edge("Chemistry Physics Lecture Theater","Electronics Lab",10),
                new Graph.Edge("Chemistry Physics Lecture Theater","Phys D",10),
                new Graph.Edge("Computing Main Office","Computing Lecture Room",25),
                new Graph.Edge("Computing Main Office","Mona School of Business South",125),
                new Graph.Edge("Computing Main Office","Marine Geology Unit",25),
                new Graph.Edge("Computing Main Office","Life Science Main Office",35),
                new Graph.Edge("Computing Lecture Room","Computing Main Office",25),
                new Graph.Edge("Computing Lecture Room","CR1",125),
                new Graph.Edge("Computing Lecture Room","CR2",130),
                new Graph.Edge("Computing Lecture Room","Lab2",5),
                new Graph.Edge("Computing Lecture Room","Lab1",125),
                new Graph.Edge("CR1","Pre Clinical Theater1",64),
                new Graph.Edge("CR1","Science Lecture Theater",64),
                new Graph.Edge("CR1","Lab2",100),
                new Graph.Edge("CR1","Lab1",4),
                new Graph.Edge("CR1","CR2",3),
                new Graph.Edge("CR2","Lab1",4),
                new Graph.Edge("CR2","CR1",4),
                new Graph.Edge("CR2","Pre Clinical Theater1",64),
                new Graph.Edge("CR2","Science Lecture Theater",64),
                new Graph.Edge("CR2","Lab2",64),
                new Graph.Edge("Lab1","Pre Clinical Theater1",64),
                new Graph.Edge("Lab1","Software Engineering Lab",24),
                new Graph.Edge("Lab2","Computing Lecture Room",8),
                new Graph.Edge("Lab2","CR1",98),
                new Graph.Edge("Lab2","CR2",88),
                new Graph.Edge("Software Engineering Lab","Pre Clinical Theater1",85),
                new Graph.Edge("Software Engineering Lab","CR1",35),
                new Graph.Edge("Software Engineering Lab","CR2",30),
                new Graph.Edge("Room 1","Mona School of Business South",111),
                new Graph.Edge("Room 2","Mona School of Business South",111),
                new Graph.Edge("Room 3","Mona School of Business South",111),
                new Graph.Edge("Room 4","Mona School of Business South",111),
                new Graph.Edge("Room 5","Mona School of Business South",111),
                new Graph.Edge("Room 6","Mona School of Business South",111),
                new Graph.Edge("Museum","Mona School of Business South",111),
                new Graph.Edge("Marine Geology Unit","Computing Main Office",42),
                new Graph.Edge("Marine Geology Unit","Inter-faculty Lecture Theater",42),
                new Graph.Edge("Marine Geology Unit","Law Faculty Main Office",242),
                new Graph.Edge("Marine Geology Unit","Bucks",142),
                new Graph.Edge("Lab 1","Mona School of Business South",111),
                new Graph.Edge("Lab 2","Mona School of Business South",111),
                new Graph.Edge("Lab 3","Mona School of Business South",111),
                new Graph.Edge("Mona School of Business South","SR  1 - 23",25),
                new Graph.Edge("Mona School of Business South","Room 1",111),
                new Graph.Edge("Mona School of Business South","Room 2",111),
                new Graph.Edge("Mona School of Business South","Room 3",111),
                new Graph.Edge("Mona School of Business South","Room 4",111),
                new Graph.Edge("Mona School of Business South","Room 5",111),
                new Graph.Edge("Mona School of Business South","Room 6",111),
                new Graph.Edge("Mona School of Business South","Museum",111),
                new Graph.Edge("Mona School of Business South","Lab 1",111),
                new Graph.Edge("Mona School of Business South","Lab 2",111),
                new Graph.Edge("Mona School of Business South","Lab 3",111),
                new Graph.Edge("Life Science Main Office","Marine Geology Unit",64),
                new Graph.Edge("Life Science Lecture Theater 1","Marine Geology Unit",64),
                new Graph.Edge("Life Science Lecture Theater 2","Life Science Lecture Theater 3",25),
                new Graph.Edge("Life Science Lecture Theater 3","Marine Geology Unit",64),
                new Graph.Edge("Life Science Lecture Theater 4","Marine Geology Unit",64),
                new Graph.Edge("Life Science Lecture Theater 5","Life Science Lecture Theater 4",20),
                new Graph.Edge("Aquatic Sciences Lab","Pre Clinical Theater1",104),
                new Graph.Edge("Block A","Pre Clinical Theater1",106),
                new Graph.Edge("Block A","Lab2",16),
                new Graph.Edge("Block A","Life Science Main Office",6),
                new Graph.Edge("Block B","Pre Clinical Theater1",120),
                new Graph.Edge("Block C","Pre Clinical Theater1",130),
                new Graph.Edge("Block D","Pre Clinical Theater1",135),
                new Graph.Edge("Block E","Pre Clinical Theater1",130),
                new Graph.Edge("Math Main Office","Pre Clinical Theater1",43),
                new Graph.Edge("Math Main Office","Science Lecture Theater",83),
                new Graph.Edge("Math Main Office","Math Lecture theater 1",1),
                new Graph.Edge("Math Main Office","Math Lecture theater 2",5),
                new Graph.Edge("Math Main Office","Math Lecture theater 3",6),
                new Graph.Edge("Math Main Office","Postgrad Room 1",6),
                new Graph.Edge("Math Main Office","Postgrad Room 2",7),
                new Graph.Edge("Math Main Office","Postgrad Room 3",9),
                new Graph.Edge("Math Main Office","Math Lab",20),
                new Graph.Edge("Math Main Office","Chemistry Main Office",20),
                new Graph.Edge("Math Main Office","Chemistry Lecture Theater 5",20),
                new Graph.Edge("Math Lab","Math Main Office",5),
                new Graph.Edge("Postgrad Room 1","Math Main Office",20),
                new Graph.Edge("Postgrad Room 2","Math Main Office",25),
                new Graph.Edge("Postgrad Room 3","Math Main Office",20),
                new Graph.Edge("Physics Main Office","Science Library",80),
                new Graph.Edge("Phys A","Science Library",40),
                new Graph.Edge("Phys B","Science Library",40),
                new Graph.Edge("Phys C","Science Library",40),
                new Graph.Edge("Phys A","Math Main Office",40),
                new Graph.Edge("Phys B","Phys A",10),
                new Graph.Edge("Phys C","Phys B",15),
                new Graph.Edge("Phys D","Electronics Lab",16),
                new Graph.Edge("Electronics Lab","Phys D",16),
                new Graph.Edge("Virtual Lab","Phys D",16),
                new Graph.Edge("Earthquake Unit","Phys D",16),
                new Graph.Edge("Electronics Unit","Phys D",23),
                new Graph.Edge("Engineering Main Office","Pre Clinical Theater1",101),
                new Graph.Edge("Engineering Lecture Theater 1","Pre Clinical Theater1",16),
                new Graph.Edge("Engineering Lecture Theater 2","Pre Clinical Theater1",17),
                new Graph.Edge("Engineering Lecture Theater 3","Pre Clinical Theater1",19),
                new Graph.Edge("Engineering Lecture Theater 4","Pre Clinical Theater1",19),
                new Graph.Edge("Engineering Lecture Theater 5","Pre Clinical Theater1",18),
                new Graph.Edge("Electronics Engineering Lab","Pre Clinical Theater1",101),
                new Graph.Edge("Humanities Gazebos","BeeHive",10),
                new Graph.Edge("Humanities Gazebos","Bank of Nova Scotia",40),
                new Graph.Edge("Humanities Gazebos","Main Library Stall",20),
                new Graph.Edge("Nursing Gazebos","Mona Information Technology Services",100),
                new Graph.Edge("Nursing Gazebos","School of Nursing",9),
                new Graph.Edge("Nursing Gazebos","UWI Health Center",30),
                new Graph.Edge("Science and Tech Gazebos","Juici Patties",15),
                new Graph.Edge("Juici Patties","Science and Tech Gazebos",15),
                new Graph.Edge("Phys C","Science and Tech Gazebos",15),
                new Graph.Edge("Inter-faculty Lecture Theater","Science and Tech Gazebos",35),
                new Graph.Edge("Science and Tech Gazebos","Inter-faculty Lecture Theater",35),
                new Graph.Edge("Law Gazebos","Mona School of Business North",50),
                new Graph.Edge("Mona School of Business Gazebos","Mona School of Business North",20),
                new Graph.Edge("Commuting Lounge Gazebos","Humanities Gazebos",100),
                new Graph.Edge("Chancellor Hall Office","Block X",25),
                new Graph.Edge("Block Aye","Block Che'",35),
                new Graph.Edge("Block Aye","Chancellor Hall Office",5),
                new Graph.Edge("Block Aye","Kentucky Fried Chicken",48),
                new Graph.Edge("Block Aye","Bank of Nova Scotia",66),
                new Graph.Edge("Block Aye","Block Runci",15),
                new Graph.Edge("Block Runci","Block Aye",25),
                new Graph.Edge("Block Runci","Block Dynamite",15),
                new Graph.Edge("Block Che'","Block X",110),
                new Graph.Edge("Block Che'","Block Chalise",80),
                new Graph.Edge("Block Che'","Block Dynamite",30),
                new Graph.Edge("Block Dynamite","Block Runci",35),
                new Graph.Edge("Block Dynamite","Tower 5",15),
                new Graph.Edge("Block Dynamite","Block Stallion",25),
                new Graph.Edge("Block X","Block Aye",98),
                new Graph.Edge("NELT","School of Education",90),
                new Graph.Edge("NELT","National Commercial Bank",162),
                new Graph.Edge("NELT","Student Administration Services",50),
                new Graph.Edge("NELT","National Commercial Bank",150),
                new Graph.Edge("Caribbean Studies","Commuting Students Lounge",80),
                new Graph.Edge("English Lit","Commuting Students Lounge",80),
                new Graph.Edge("School of Education","Commuting Students Lounge",90),
                new Graph.Edge("Modern Language and literature","Commuting Students Lounge",70),
                new Graph.Edge("Library and Information Studies","Commuting Students Lounge",56),
                new Graph.Edge("School of Education Lecture Theater","Commuting Students Lounge",10),
                new Graph.Edge("Commuting Students Lounge","Caribbean Studies",80),
                new Graph.Edge("Commuting Students Lounge","English Lit",80),
                new Graph.Edge("Commuting Students Lounge","School of Education",90),
                new Graph.Edge("Commuting Students Lounge","Modern Language and literature",70),
                new Graph.Edge("Commuting Students Lounge","Library and Information Studies",56),
                new Graph.Edge("Commuting Students Lounge","School of Education Lecture Theater",10),
                new Graph.Edge("Commuting Students Lounge","N 1",20),
                new Graph.Edge("Commuting Students Lounge","N 2",30),
                new Graph.Edge("Commuting Students Lounge","N 3",32),
                new Graph.Edge("Commuting Students Lounge","N 4",36),
                new Graph.Edge("Commuting Students Lounge","Bank of Nova Scotia",50),
                new Graph.Edge("Law Faculty Main Office","Mona School of Business North",86),
                new Graph.Edge("Lecture Room 1A","Faculty Main Office",5),
                new Graph.Edge("Lecture Room 2B","Lecture Room 1A",10),
                new Graph.Edge("Lecture Room 2B","Lecture Room 1",10),
                new Graph.Edge("Lecture Room 1","Lecture Room 2",15),
                new Graph.Edge("Lecture Room 2","Lecture Room 3",1),
                new Graph.Edge("Lecture Room 2","Seminar Room 2",10),
                new Graph.Edge("Lecture Room 3","Lecture Room 1",10),
                new Graph.Edge("Seminar Room 1","Lecture Room 3",1),
                new Graph.Edge("Seminar Room 2","Seminar Room 1",1),
                new Graph.Edge("Law Faculty Main Office","Law Library",86),
                new Graph.Edge("Lecture Room 1A","Law Library",5),
                new Graph.Edge("Lecture Room 2B","Law Library",10),
                new Graph.Edge("Lecture Room 2B","Law Library",10),
                new Graph.Edge("Law Library","Lecture Room 3",1),
                new Graph.Edge("Law Library","Seminar Room 2",10),
                new Graph.Edge("Law Library","Lecture Room 1",10),
                new Graph.Edge("Law Library","Lecture Room 3",1),
                new Graph.Edge("Law Library","Seminar Room 1",1),
                new Graph.Edge("Science Lecture Theater","Pre Clinical Theater1",15),
                new Graph.Edge("Pre Clinical Theater1","Science Lecture Theater",15),
                new Graph.Edge("Pre Clinical Theater1","Engineering Main Office",5),
                new Graph.Edge("Pre Clinical Theater1","Engineering Lecture Theater 1",10),
                new Graph.Edge("Pre Clinical Theater1","Engineering Lecture Theater 2",4),
                new Graph.Edge("Pre Clinical Theater1","Engineering Lecture Theater 3",11),
                new Graph.Edge("Pre Clinical Theater1","Engineering Lecture Theater 4",16),
                new Graph.Edge("Pre Clinical Theater1","Engineering Lecture Theater 5",13),
                new Graph.Edge("Pre Clinical Theater1","Electronics Engineering Lab",15),
                new Graph.Edge("Pre Clinical Theater1","CR1",25),
                new Graph.Edge("Pre Clinical Theater1","CR2",25),
                new Graph.Edge("Pre Clinical Theater1","Lab1",55),
                new Graph.Edge("Pre Clinical Theater1","Lab2",125),
                new Graph.Edge("Inter-faculty Lecture Theater","Juici Patties",69),
                new Graph.Edge("Inter-faculty Lecture Theater","Law Faculty Main Office",269),
                new Graph.Edge("Inter-faculty Lecture Theater","Science Library",79),
                new Graph.Edge("Inter-faculty Lecture Theater","Student Administration Services",169),
                new Graph.Edge("Inter-faculty Lecture Theater","Assembly Hall",110),
                new Graph.Edge("Inter-faculty Lecture Theater","Book Shop",130),
                new Graph.Edge("Inter-faculty Lecture Theater","Mona School of Business South",90),
                new Graph.Edge("Inter-faculty Lecture Theater","Mona School of Business North",230),
                new Graph.Edge("Inter-faculty Lecture Theater","Bursary",130),
                new Graph.Edge("Inter-faculty Lecture Theater","Marine Geology Unit",70),
                new Graph.Edge("Biology Lecture Theater","Block A",25),
                new Graph.Edge("Social Science Lecture Theater","Student Administration Services",58),
                new Graph.Edge("Social Science Lecture Theater","Bursary",68),
                new Graph.Edge("Social Science Lecture Theater","SR  1 - 23",68),
                new Graph.Edge("Social Science Lecture Theater","Mona School of Business North",168),
                new Graph.Edge("Social Science Lecture Theater","Mona School of Business South",68),
                new Graph.Edge("Social Science Lecture Theater","Law Faculty Main Office",268),
                new Graph.Edge("Social Science Lecture Theater","Lecture Room 1A",260),
                new Graph.Edge("Social Science Lecture Theater","Lecture Room 2B",268),
                new Graph.Edge("Social Science Lecture Theater","Lecture Room 1",268),
                new Graph.Edge("GLT 1","Mona School of Business North",10),
                new Graph.Edge("GLT 2","Mona School of Business North",11),
                new Graph.Edge("GLT 3","Mona School of Business North",12),
                new Graph.Edge("SR  1 - 23","Mona School of Business South",25),
                new Graph.Edge("Psychology Unit","Mona School of Business North",10),
                new Graph.Edge("New Arts Block","Commuting Students Lounge",60),
                new Graph.Edge("Main Library","Kentucky Fried Chicken",121),
                new Graph.Edge("Main Library","Main Library Stall",80),
                new Graph.Edge("Main Library","Block Aye",180),
                new Graph.Edge("Main Library","Student Administration Services",190),
                new Graph.Edge("Main Library","Mona School of Business South",280),
                new Graph.Edge("Main Library","Mona School of Business North",480),
                new Graph.Edge("Main Library","Bank of Nova Scotia",126),
                new Graph.Edge("Main Library","Social Science Lecture Theater",180),
                new Graph.Edge("Main Library","Med Library",220),
                new Graph.Edge("Main Library","Social Science Stall",80),
                new Graph.Edge("Main Library","Jamaica National",60),
                new Graph.Edge("Science Library","Inter-faculty Lecture Theater",81),
                new Graph.Edge("Science Library","Phys A",81),
                new Graph.Edge("Science Library","Pre Clinical Theater1",11),
                new Graph.Edge("Science Library","Math Main Office",13),
                new Graph.Edge("Science Library","Science and Tech Stall 1",13),
                new Graph.Edge("Science Library","Science and Tech Stall 2",13),
                new Graph.Edge("Pre Clinical Theater1","Science Library",11),
                new Graph.Edge("Social Science Library","Dukunoo Deli",48),
                new Graph.Edge("Kentucky Fried Chicken","Pages Cafe'",10),
                new Graph.Edge("Kentucky Fried Chicken","Bank of Nova Scotia",40),
                new Graph.Edge("Kentucky Fried Chicken","Jamaica National",20),
                new Graph.Edge("Jamaica National","Kentucky Fried Chicken",20),
                new Graph.Edge("Jamaica National","Main Library",60),
                new Graph.Edge("The Spot","Yao",10),
                new Graph.Edge("Yao","The Spot",10),
                new Graph.Edge("Juici Patties","Science Library",105),
                new Graph.Edge("Juici Patties","Physics Main Office",65),
                new Graph.Edge("Juici Patties","Inter-faculty Lecture Theater",55),
                new Graph.Edge("Juici Patties","Science and Tech Stall 1",30),
                new Graph.Edge("Juici Patties","Science and Tech Stall 2",35),
                new Graph.Edge("Juici Patties","Assembly Hall",95),
                new Graph.Edge("Juici Patties","Book Shop",55),
                new Graph.Edge("Pages Cafe'","Main Library",125),
                new Graph.Edge("BeeHive","Humanities Stall",38),
                new Graph.Edge("BeeHive","Book Shop",58),
                new Graph.Edge("BeeHive","Mona Information Technology Services",70),
                new Graph.Edge("BeeHive","Humanities Gazebos",50),
                new Graph.Edge("Dukunoo Deli","Lecture Room 1A",163),
                new Graph.Edge("Dukunoo Deli","Mona School of Business South",83),
                new Graph.Edge("Dukunoo Deli","Mona School of Business North",63),
                new Graph.Edge("Dukunoo Deli","Med Library",300),
                new Graph.Edge("Med Library","Dukunoo Deli",300),
                new Graph.Edge("Med Library","Mona School of Business North",200),
                new Graph.Edge("Med Library","Kentucky Fried Chicken",400),
                new Graph.Edge("Med Library","Surgery",400),
                new Graph.Edge("Med Library","Micro Biology",400),
                new Graph.Edge("Old Library","U.W.I Credit Union",40),
                new Graph.Edge("Old Library","Students Union",200),
                new Graph.Edge("U.W.I Credit Union","Old Library",40),
                new Graph.Edge("Bucks","Lecture Room 1A",61),
                new Graph.Edge("Faculty Office","Lecture Room 1A",10),
                new Graph.Edge("Hotel and Tourism","Lecture Room 1A",80),
                new Graph.Edge("Economics","Social Science Lecture Theater",28),
                new Graph.Edge("Government","Social Science Lecture Theater",28),
                new Graph.Edge("Mona School of Business North","Lecture Room 1A",63),
                new Graph.Edge("Mona School of Business North","GLT 1",10),
                new Graph.Edge("Mona School of Business North","GLT 2",11),
                new Graph.Edge("Mona School of Business North","GLT 3",12),
                new Graph.Edge("Mona School of Business North","Med Library",40),
                new Graph.Edge("Mona School of Business North","Law Gazebos",25),
                new Graph.Edge("Mona School of Business South","Dukunoo Deli",51),
                new Graph.Edge("Sociology and Social Work","Mona School of Business North",10),
                new Graph.Edge("Psychology Unit","Mona School of Business North",25),
                new Graph.Edge("Institute for Gender and Development","Mona School of Business North",15),
                new Graph.Edge("Main Library Stall","Main Library",92),
                new Graph.Edge("Main Library Stall","Commuting Students Lounge",42),
                new Graph.Edge("N 1","Commuting Students Lounge",30),
                new Graph.Edge("N 1","N 2",10),
                new Graph.Edge("N 1","N 4",10),
                new Graph.Edge("N 2","N 1",10),
                new Graph.Edge("N 2","N 3",4),
                new Graph.Edge("N 3","N 2",10),
                new Graph.Edge("N 4","N 3",10),
                new Graph.Edge("Humanities Stall","BeeHive",58),
                new Graph.Edge("Humanities Stall","N 1",17),
                new Graph.Edge("Humanities Stall","Commuting Students Lounge",17),
                new Graph.Edge("Social Science Stall","Social Science Lecture Theater",66),
                new Graph.Edge("Science and Tech Stall 1","Science Library",24),
                new Graph.Edge("Science and Tech Stall 2","Science Library",30),
                new Graph.Edge("Science and Tech Stall 1","Pre Clinical Theater1",36),
                new Graph.Edge("Science and Tech Stall 2","Pre Clinical Theater1",28),
                new Graph.Edge("Community Health Psychiatry","Child and Adolescents",10),
                new Graph.Edge("Community Health Psychiatry","Medicine",12),
                new Graph.Edge("Child and Adolescents","Community Health Psychiatry ",14),
                new Graph.Edge("Medicine ","Community Health Psychiatry ",13),
                new Graph.Edge("Micro Biology","Child and Adolescents",12),
                new Graph.Edge("Micro Biology","Med Library",150),
                new Graph.Edge("Surgery","Child and Adolescents",13),
                new Graph.Edge("Surgery","Med Library",140),
                new Graph.Edge("UWI Health Center","School of Nursing",10),
                new Graph.Edge("UWI Health Center","Students Union",300),
                new Graph.Edge("School of Nursing","Child and Adolescents",13),
                new Graph.Edge("School of Nursing","UWI Health Center",10),
                new Graph.Edge("School of Nursing","Bank of Nova Scotia",100),
                new Graph.Edge("School of Nursing","Students Union",280),
                new Graph.Edge("School of Nursing","Mona Information Technology Services",200),
                new Graph.Edge("School of Nursing","Nursing Gazebos",9),
                new Graph.Edge("Radiology","Child and Adolescents",13),
                new Graph.Edge("Anaesthesia","Child and Adolescents",11),
                new Graph.Edge("Intensive Care","Child and Adolescents",10),
                new Graph.Edge("Obstetrics Gynaecology","Child and Adolescents",13),
                new Graph.Edge("ABC Hall Office","ABC Block C",5),
                new Graph.Edge("ABC Hall Office","University Hospital",41),
                new Graph.Edge("ABC Block A","ABC Block B",13),
                new Graph.Edge("University Hospital","ABC Hall Office",14),
                new Graph.Edge("Med Library","University Hospital",180),
                new Graph.Edge("ABC Block B","ABC Block C",13),
                new Graph.Edge("ABC Block B","ABC Block A",13),
                new Graph.Edge("ABC Block C","ABC Block B",13),
                new Graph.Edge("ABC Block A","Med Library",80),
                new Graph.Edge("Med Library","ABC Block A",80),
                new Graph.Edge("University Hospital","Med Library",50),
                new Graph.Edge("University Hospital","Main Library",180),
                new Graph.Edge("New Post Grad","Old PostGrad",70),
                new Graph.Edge("New Post Grad","Students Union",120),
                new Graph.Edge("New Post Grad","138 Office",12),
                new Graph.Edge("Old PostGrad","New Post Grad",180),
                new Graph.Edge("Old PostGrad","Students Union",200),
                new Graph.Edge("Old PostGrad","138 Office",170),
                new Graph.Edge("138 Office","Students Union",60),
                new Graph.Edge("138 Office","Old PostGrad",12),
                new Graph.Edge("138 Office","T 1",14),
                new Graph.Edge("T 1","138 Office",15),
                new Graph.Edge("T 1","T 2",16),
                new Graph.Edge("T 1","T 3",15),
                new Graph.Edge("T 2","T 1",14),
                new Graph.Edge("T 3","T 1",13),
                new Graph.Edge("Tower Hall Office","Tower 1",40),
                new Graph.Edge("Tower Hall Office","University Hospital",80),
                new Graph.Edge("Tower Hall Office","Tower 2",100),
                new Graph.Edge("Tower 1","Tower Hall Office",30),
                new Graph.Edge("Tower 1","Tower 2",30),
                new Graph.Edge("Tower 2","Tower 3",43),
                new Graph.Edge("Tower 2","Tower Hall Office",43),
                new Graph.Edge("Tower 3","Tower 4",32),
                new Graph.Edge("Tower 4","Tower 3",32),
                new Graph.Edge("Tower 5","Tower 2",70),
                new Graph.Edge("Tower 5","Block Che'",90),
                new Graph.Edge("Tower 5","Block Dynamite",15),
                new Graph.Edge("Tower 5","Block Stallion",26),
                new Graph.Edge("Taylor Hall Office","Block Roosters",10),
                new Graph.Edge("Taylor Hall Office","Block Stallion",10),
                new Graph.Edge("Taylor Hall Office","Tower 5",40),
                new Graph.Edge("Block Attica","Block Roosters",10),
                new Graph.Edge("Block Attica","Block G",30),
                new Graph.Edge("Block Attica","Block Butchers",27),
                new Graph.Edge("Block Butchers","Block Stallion",40),
                new Graph.Edge("Block Butchers","Block G",20),
                new Graph.Edge("Block Butchers","Block Attica",30),
                new Graph.Edge("Block Roosters","Taylor Hall Office",10),
                new Graph.Edge("Block Stallion","Taylor Hall Office",10),
                new Graph.Edge("Block Stallion","Block Dynamite",23),
                new Graph.Edge("Block Stallion","Tower 5",28),
                new Graph.Edge("Block Stallion","Block Butchers",30),
                new Graph.Edge("Block G","Block Attica",39),
                new Graph.Edge("Block G","Block Butchers",30),
                new Graph.Edge("Mary Seacole Hall Office","Commuting Students Lounge",40),
                new Graph.Edge("Mary Seacole Hall Office","Bank of Nova Scotia",70),
                new Graph.Edge("Mary Seacole Hall Office","Crowd Block",30),
                new Graph.Edge("Mary Seacole Hall Office","Seacole Block Dynamite",15),
                new Graph.Edge("Jade Block","Great Block",2),
                new Graph.Edge("Jade Block","Hype Block",2),
                new Graph.Edge("Great Block","Jade Block",2),
                new Graph.Edge("Great Block","Crowd Block",2),
                new Graph.Edge("Hype Block","Jade Block",2),
                new Graph.Edge("Hype Block","Seacole Block Dynamite",2),
                new Graph.Edge("Crowd Block","Seacole Block Dynamite",2),
                new Graph.Edge("Crowd Block","Great Block",2),
                new Graph.Edge("Seacole Block Dynamite","Crowd Block",2),
                new Graph.Edge("Seacole Block Dynamite","Mary Seacole Hall Office",15),
                new Graph.Edge("Crowd Block","Mary Seacole Hall Office",30),
                new Graph.Edge("Hype Block","Great Block",24),
                new Graph.Edge("Great Block","Hype Block",24),
                new Graph.Edge("Rex Hall Office","Cluster 1",10),
                new Graph.Edge("Rex Hall Office","Cluster 2",20),
                new Graph.Edge("Rex Hall Office","Cluster 3",30),
                new Graph.Edge("Rex Hall Office","Cluster 4",40),
                new Graph.Edge("Rex Hall Office","Cluster 5",50),
                new Graph.Edge("Rex Hall Office","Cluster 6",60),
                new Graph.Edge("Rex Hall Office","Cluster 9",70),
                new Graph.Edge("Rex Hall Office","Cluster 8",20),
                new Graph.Edge("Rex Hall Office","Old PostGrad",150),
                new Graph.Edge("Cluster 1","Cluster 2",10),
                new Graph.Edge("Cluster 1","Rex Hall Office",10),
                new Graph.Edge("Cluster 2","Cluster 1",10),
                new Graph.Edge("Cluster 2","Cluster 3",10),
                new Graph.Edge("Cluster 3","Cluster 2",10),
                new Graph.Edge("Cluster 3","Cluster 4",10),
                new Graph.Edge("Cluster 4","Cluster 3",10),
                new Graph.Edge("Cluster 4","UWI Health Center",300),
                new Graph.Edge("Cluster 4","Mona Information Technology Services",300),
                new Graph.Edge("Cluster 4","Students Union",150),
                new Graph.Edge("Cluster 4","Rex Hall Office",20),
                new Graph.Edge("Cluster 4","Cluster 5",10),
                new Graph.Edge("Cluster 5","Cluster 4",10),
                new Graph.Edge("Cluster 5","Cluster 6",10),
                new Graph.Edge("Cluster 5","Rex Hall Office",10),
                new Graph.Edge("Cluster 6","Cluster 7",10),
                new Graph.Edge("Cluster 6","Cluster 5",10),
                new Graph.Edge("Cluster 7","Cluster 8",10),
                new Graph.Edge("Cluster 7","Cluster 6",10),
                new Graph.Edge("Cluster 8","Cluster 9",10),
                new Graph.Edge("Cluster 8","Cluster 7",10),
                new Graph.Edge("Cluster 9","Cluster 8",10),
                new Graph.Edge("Cluster 9","Rex Hall Office",10),
                new Graph.Edge("Irvin Hall Office","Block Alpha",10),
                new Graph.Edge("Block Alpha","Irvin Hall Office",10),
                new Graph.Edge("Block Bears","Block Alpha",12),
                new Graph.Edge("Block Chalise","Block Che'",72),
                new Graph.Edge("Freshers Block","Tower 1",40),
                new Graph.Edge("Freshers Block","Block Bears",50),
                new Graph.Edge("Freshers Block","Tower Hall Office",9),
                new Graph.Edge("Block Chalise","Block Bears",12),
                new Graph.Edge("Block Chalise","Freshers Block",10),
                new Graph.Edge("Block Bears","Freshers Block",12),
                new Graph.Edge("Block Alpha","Block Chalise",12),
                new Graph.Edge("Preston Hall Office","Cluster Olympia",10),
                new Graph.Edge("Preston Hall Office","Cluster Sherwood Manor",27),
                new Graph.Edge("Preston Hall Office","Students Union",120),
                new Graph.Edge("Preston Hall Office","Rex Hall Office",140),
                new Graph.Edge("Preston Hall Office","Old PostGrad",130),
                new Graph.Edge("Cluster Amsterdam","Cluster Olympia",20),
                new Graph.Edge("Cluster Amsterdam","Cluster Burgplatz",20),
                new Graph.Edge("Cluster Amsterdam","Cluster La Maison",20),
                new Graph.Edge("Cluster Belqique","Cluster Olympia",20),
                new Graph.Edge("Cluster Belqique","Cluster Amsterdam",20),
                new Graph.Edge("Cluster Belqique","Cluster La Maison",20),
                new Graph.Edge("Cluster Burgplatz","Cluster Amsterdam",20),
                new Graph.Edge("Cluster Burgplatz","Cluster La Maison",20),
                new Graph.Edge("Cluster Einheit","Cluster Regensen",20),
                new Graph.Edge("Cluster Einheit","Cluster Italia",20),
                new Graph.Edge("Cluster Italia","Cluster Regensen",20),
                new Graph.Edge("Cluster Italia","Cluster Einheit",20),
                new Graph.Edge("Cluster Italia","Cluster Los Matadores",20),
                new Graph.Edge("Cluster Los Matadores","Cluster Italia",20),
                new Graph.Edge("Cluster Los Matadores","Preston Hall Office",20),
                new Graph.Edge("Cluster Los Matadores","Cluster Olympia",20),
                new Graph.Edge("Cluster Sherwood Manor","Preston Hall Office",20),
                new Graph.Edge("Cluster Regensen","Cluster Einheit",20),
                new Graph.Edge("Cluster Regensen","Cluster Italia",20),
                new Graph.Edge("Cluster Olympia","Preston Hall Office",20),
                new Graph.Edge("Cluster Olympia","Cluster Amsterdam",20),
                new Graph.Edge("Cluster Olympia","Cluster La Maison",20),
                new Graph.Edge("Cluster La Maison","Cluster Amsterdam",20),
                new Graph.Edge("Cluster La Maison","Cluster Olympia",20),
                new Graph.Edge("Cluster La Maison","Cluster Burgplatz",20),
                new Graph.Edge("Cluster La Maison","Cluster Belqique",20),


        };
        public String START ;
        public String END ;


        public void main(String[] args) {
                Graph g = new Graph(GRAPH);
                g.dijkstra(START);
                g.printPath(END);
//        g.printAllPaths();
        }
}
